apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment # name of deployment
  labels: # add lables
    app: my-application
    type: frontend
spec:
  selector:
    matchLabels:
      app: my-app
    replicas: 3
    template:
      metedata:
        name: nginx-2
        labels: 
          app: my-app
      spec:
        containers:
          - name: nginx
            image: nginx

